preload = /home/rahul/Pictures/wallpapers/vulcan.jpg
preload = /home/rahul/Pictures/wallpapers/wallpaper1.jpg
preload = /home/rahul/Pictures/wallpapers/wallpaper2.jpg
preload = /home/rahul/Pictures/wallpapers/wallpaper3.jpg
preload = /home/rahul/Pictures/wallpapers/wallpaper4.jpg

wallpaper {
    monitor = HDMI-A-1
    path = /home/rahul/Pictures/wallpapers/vulcan.jpg
    fit_mode = cover
}

splash = false
ipc = on
